# Dependencies
markdown:         redcarpet
redcarpet:
  extension:      ["fenced_code_blocks", "hard_wrap", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify", "no_intra_emphasis"]
highlighter:      pygments
plugins:          ["jekyll-paginate", "jekyll-gist"]

# Permalinks
permalink:        pretty

# Setup
title:            Webb's Tech Note
tagline:          'Web developement notes'
description:      'Hello, World!'
url:              http://uwaylu.github.io/
baseurl:          /

author:           Webb Lu
name:             'Webb Lu'
url:              http://uwaylu.github.io/

paginate:         5

# Custom vars
build:            {date: 2017.07}
github:           uWayLu
