# Dependencies
markdown:         kramdown
redcarpet:
  extensions:      ["fenced_code_blocks", "hard_wrap", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify", "no_intra_emphasis"]
highlighter:      rouge
plugins:          ["jekyll-paginate", "jekyll-gist"]

# Permalinks
permalink:        pretty

# Setup
title:            Webb's Tech Note
tagline:          'Web developement notes'
description:      'Learning notes of PHP, Javascript, and everything about coding.'
baseurl:          
resources_url:    /public

author:           Webb Lu
name:             'Webb Lu'
url:              https://uwaylu.github.io/jekyll-hyde

paginate:         5

# Custom vars
build:            {date: 2017.07}
github_username:  uWayLu
